
--Buscar transacciones  auxiliares por DI
SELECT TAT.ID_AUX_TRANSAC_DET,
  TAT.AUTORIZACION,
  TAT.CADENA,
  TAT.CANAL,
  TAT.CODACTUACION,
  TAT.DESCANAL,
  TAT.DN,
  TAT.FECHA,
  TAT.FECHATRANSACCION,
  TAT.MONTO,
  TAT.NIVEL,
  TAT.SITE,
  CE.NOMBRE ESTADO_TRANSACCION,
  CS.COD_DISTRIBUIDOR DI,
  CTF.DESCRIPCION TIPO_FACTURA,
  TAT.ID_TIPO_PRODUCTO,
  CTP.NOMBRE NAME_TIPO_PRODUCTOS
FROM AFT_AUX_TRANSACCION TAT 
INNER JOIN AFC_ESTADO CE on CE.ID_ESTADO = TAT.ID_ESTADO
INNER JOIN AFC_SOCIO CS on CS.ID_SOCIO_COMER = TAT.ID_SOCIO_COMER 
INNER JOIN AFC_TIPO_FACTURA CTF on CTF.ID_TIPO_FACTURA = TAT.ID_TIPO_FACTURA
INNER JOIN AFC_TIPO_PRODUCTO CTP on CTP.ID_TIPO_PRODUCTO = TAT.ID_TIPO_PRODUCTO
WHERE CS.COD_DISTRIBUIDOR = ''
;


--Buscar facturas por distribuidor 
SELECT 	
    GS.ID_GRP_SOCIO,
    CS.ID_SOCIO_COMER,
    CD.CODIGO DEUDOR_SAP,
    CTF.NOMBRE TIPO_FACTURA,
    CS.COD_DISTRIBUIDOR,
  	CS.NOMBRE NOMBRE_DISTRIBUIDOR,
  	CS.ID_TIPO_SOCIO,
    CE.NOMBRE ESTADO,
    TFH.ID_FACTURA_HEAD,
    TFH.NUM_TRANSACCIONES,
    TFH.TOTAL,
    CTP.CODIGO,
    CTP.NOMBRE TIPO_PRODUCTO,
    TFH.FECHA_EMISION,
    TFH.IMPORTE_SIN_IVA,
    TFH.COMISION_SIN_IVA
FROM AFC_SOCIO CS
INNER JOIN AFG_GRP_SOCIO GS on GS.ID_GRP_SOCIO = CS.ID_GRP_SOCIO
INNER JOIN AFC_ESTADO CE on CE.ID_ESTADO = GS.ID_ESTADO
INNER JOIN AFC_TIPO_FACTURA CTF on CTF.ID_TIPO_FACTURA = GS.ID_TIPO_FACTURA
INNER JOIN AFC_DEUDOR CD on CD.ID_DEUDOR = GS.ID_DEUDOR
INNER JOIN AFT_FACTURA_HEAD TFH on TFH.ID_GRP_SOCIO = GS.ID_GRP_SOCIO
INNER JOIN AFC_TIPO_PRODUCTO CTP on CTP.ID_TIPO_PRODUCTO = TFH.ID_TIPO_PRODUCTO
WHERE CS.COD_DISTRIBUIDOR = '90040807';


--Busqueda distribuidor por DI
SELECT 	
    GS.ID_GRP_SOCIO,
    CS.ID_SOCIO_COMER,
    CD.CODIGO DEUDOR_SAP,
    CTF.NOMBRE TIPO_FACTURA,
    CS.COD_DISTRIBUIDOR,
  	CS.NOMBRE NOMBRE_DISTRIBUIDOR,
  	CS.ID_ESTADO,
  	CS.ID_TIPO_SOCIO,
    CE.NOMBRE ESTADO
FROM AFC_SOCIO CS
INNER JOIN AFG_GRP_SOCIO GS on GS.ID_GRP_SOCIO = CS.ID_GRP_SOCIO
INNER JOIN AFC_ESTADO CE on CE.ID_ESTADO = GS.ID_ESTADO
INNER JOIN AFC_TIPO_FACTURA CTF on CTF.ID_TIPO_FACTURA = GS.ID_TIPO_FACTURA
INNER JOIN AFC_DEUDOR CD on CD.ID_DEUDOR = GS.ID_DEUDOR
WHERE CS.COD_DISTRIBUIDOR = '90040807';
